name: Deploy to Server

on:
  push:
    branches: [ main ]  # Запускать при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10  # Популярное действие для SSH
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull telegrambot main &&
            cd /home/deploy/telegrambot  # Перейти в папку проекта
            chmod +x start_bot.sh
            ./start_bot.sh
#            git pull telegrambot main     # Стянуть последние изменения
#            docker compose down      # Остановить старые контейнеры
#            docker compose up -d --build  # Пересобрать и запустить новые
#            docker image prune -f    # (Опционально) Удалить старые образы 
